name: Build and Release Pebble

on:
  push:
    tags:
      - "v*"   # e.g., v0.1, v1.0

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build on Linux/macOS
      if: matrix.os != 'windows-latest'
      run: |
        make
        mv pebble pebble-${{ matrix.os }}

    - name: Setup MSYS2 for Windows
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-gcc make

    - name: Build on Windows
      if: matrix.os == 'windows-latest'
      run: |
        mingw32-make
        mv pebble.exe pebble-windows.exe


    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: pebble-${{ matrix.os }}
        path: |
          pebble-${{ matrix.os }}
          pebble-windows.exe

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all binaries
      uses: actions/download-artifact@v4
      with:
        path: ./dist

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
